### ISSUE TITLE
External content citations/references/credits

### ISSUE THREAD

**Issue by x-delfino** [carlospolop/hacktricks-cloud#5]
Thanks for the resource. I do, however, have some concerns about the source of some of this content and lack of sufficient crediting of the original authors. 

For example, the following two articles are identical:
https://hackingthe.cloud/aws/general-knowledge/connection-tracking/
https://cloud.hacktricks.xyz/pentesting-cloud/aws-security/aws-basic-information/connection-tracking

I don't see anything in the hacktricks article referencing the original source or crediting the original author. I feel this is particularly relevant considering that hacktricks are seeking sponsorship from both individuals and organisations to support the project.

**Comment by carlospolop** [comment]
Hi @x-delfino,
I appreciate your concern, it's very important to reference everything and I'm sorry that page is lacking that on, I'm surprised thb.

I have already talked to the creator of [https://hackingthe.cloud](https://hackingthe.cloud/). All content from there in hacktricks will be refactored and if references are lacking they will be added :)
In 1-2 weeks, please feel free to let me know if you still find content lacking references like this one.
